### ISSUE TITLE
./evidence deploy user.jks '123456' '123456'  执行命令报错

### ISSUE THREAD

**Issue by Blackcatfish** [FISCO-BCOS/evidenceSample#15]
Exception in thread "main" java.lang.Exception
        at org.bcos.channel.client.Service.run(Service.java:242)
        at org.bcos.evidence.app.BcosApp.loadConfig(BcosApp.java:56)
        at org.bcos.evidence.app.Main.main(Main.java:24)
不知道是什么原因导致的 大神帮帮忙

**Comment by Blackcatfish** [comment]
区块网络是内网的 然后部署的节点是按照https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/sample这个上面部署的按照上面的做法两台的节点是通了的
想放入存证案例运行一直包上面的错误不知道如何解决 请大神帮个忙

**Comment by fisco-dev** [comment]
https://github.com/FISCO-BCOS/web3sdk/wiki/web3sdk-debug

**Comment by Ainimomoda** [comment]
@Blackcatfish  你好，最近在部署时也遇到了类似问题。按照https://github.com/FISCO-BCOS/evidenceSample 部署运行，然后报错。请问你解决了吗？

#./evidence deploy user.jks '123456' '123456'
Exception in thread "main" java.lang.NoClassDefFoundError: org/fisco/bcos/web3j/protocol/Web3jService
	at org.bcos.evidence.app.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: org.fisco.bcos.web3j.protocol.Web3jService
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
